### ISSUE TITLE
Negative password expiration if unable to connect to Domain Controller

### ISSUE THREAD

**Issue by MacDogbert** [macmule/ADPassMon#67]
Really like this tool, thanks for all of your work on it.

This issue is present when DNS resolves the Domain Controllers successfully, but the machine (and therefore the app) is unable to connect to them. It looks like the check for domain connectivity uses dig to see if there are DCs in DNS, but doesn't confirm connectivity.

Use case: An environment where DNS resolves the DCs, but doesn't allow devices to connect to those subnets without a device certificate.

Note: Maybe this isn't a common enough issue to warrant a fix, but it may be related to other reported issues regarding negative expiration dates. An additional check for connectivity may prevent this from occurring, though I don't know why the stored expireDateUnixplist value is getting updated to an incorrect value, which is very close to the SMBPasswordLastSet value.

Here is what I am seeing:
### Configuration:

> defaults read org.pmbuko.adpassmon
>     accTest = 0;
>     enableKeychainLockCheck = 1;
>     expireDateUnix = 1467652519;
>     "first_run" = 0;
>     isBehaviour2Enabled = 1;
>     "menu_title" = 54d;
>     pwdSetDate = "16926.72";
>     selectedBehaviour = 2;
>     tooltip = "Your password expires\nMon Jul  4 12:15:19 CDT 2016";
### If connected to LAN:

Tool works as intended
Expiration Date in menu bar is correct (55d)
expireDateUnix in plist is correct (1462468608)
Dig successful (multiple domain controllers returned in ANSWER section)
ping to DCs successful
Able to read msDS-UserPasswordExpiryTimeComputed successfully

> 5/11/16 11:34:33.021 AM ADPassMon[548]: Domain reachable.
> 5/11/16 11:34:33.021 AM ADPassMon[548]: Starting auto process…
> 5/11/16 11:34:33.022 AM ADPassMon[548]:   Found expireDateUnix in plist: 1462468608
> 5/11/16 11:34:33.070 AM ADPassMon[548]:   Got expireDateUnix: 1467652519
> 5/11/16 11:34:33.070 AM ADPassMon[548]:   Using msDS method
> 5/11/16 11:34:33.084 AM ADPassMon[548]:     daysUntilExp: 54.028310185185
> 5/11/16 11:34:33.091 AM ADPassMon[548]: ADPassMon password method selected
> 5/11/16 11:34:33.091 AM ADPassMon[548]: Testing Keychain Lock state...;
> 5/11/16 11:34:33.127 AM ADPassMon[548]:   Keychain unlocked...
### If connected to WiFi:

Expiration Date in menu bar is incorrect (-5d) (yes, negative 5)
expireDateUnix in plist is incorrect (1462468607)
**--The incorrect expireDateUnix is very close to the SMBPasswordLastSet value, about 78 seconds later**. I've tried tracking down the root cause for this in the code but haven't had much luck.
Dig successful (multiple domain controllers returned in ANSWER section)
ping to DCs fails (traffic cannot access DC subnets without cert)
Unable to read msDS-UserPasswordExpiryTimeComputed

> 5/11/16 11:54:35.816 AM ADPassMon[548]: Domain reachable.
> 5/11/16 11:54:35.816 AM ADPassMon[548]: Starting auto process…
> 5/11/16 11:54:35.817 AM ADPassMon[548]:   Found expireDateUnix in plist: 1467652519
> 5/11/16 11:54:45.925 AM ADPassMon[548]:   Using alt method
> 5/11/16 11:54:45.960 AM ADPassMon[548]:   New pwdSetDate (16926.72)
> 5/11/16 11:54:45.960 AM ADPassMon[548]:   ≥ plist value (1.692672E+4) so we use it
> 5/11/16 11:54:45.968 AM ADPassMon[548]:   daysUntilExp: -5.984688
> 5/11/16 11:54:45.975 AM ADPassMon[548]:   expireDateUnix: 1462468607
> 5/11/16 11:54:45.976 AM ADPassMon[548]:   expirationDate: Thursday, May 5, 2016 at 12:16:48 PM
> 5/11/16 11:54:45.982 AM ADPassMon[548]: Triggering notification…
> 5/11/16 11:54:45.983 AM ADPassMon[548]: ADPassMon password method selected
> 5/11/16 11:54:45.983 AM ADPassMon[548]: Testing Keychain Lock state...
> 5/11/16 11:54:46.017 AM ADPassMon[548]:   Keychain unlocked...
### If connected to external network (after things are working internally):

Tool works as intended
Expiration Date in menu bar is correct (55d)
expireDateUnix in plist is correct (1462468608)
Dig fails
no DCs to ping
Unable to read msDS-UserPasswordExpiryTimeComputed

> 5/11/16 12:19:40.400 PM ADPassMon[548]: Domain test timed out.
> 5/11/16 12:19:40.401 PM ADPassMon[548]: Starting auto process…
> 5/11/16 12:19:40.401 PM ADPassMon[548]:   Offline. Updating menu…
> 5/11/16 12:19:40.414 PM ADPassMon[548]: ADPassMon password method selected
> 5/11/16 12:19:40.415 PM ADPassMon[548]: Testing Keychain Lock state...
> 5/11/16 12:19:40.449 PM ADPassMon[548]:   Keychain unlocked...

**Comment by macmule** [comment]
Ah.. I've been working with some folks on Slack with similar issues.

When on wifi, what does this give:

`````` #!/bin/bash
​
smb_last_set=$(/usr/bin/dscl localhost read /Search/Users/$USER SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}' | tail -n 1)
smb_last_set_epoch=$((echo $smb_last_set/10000000-11644473600))
​
adpassmon_last_set=$(/usr/bin/defaults read org.pmbuko.ADPassMon expireDateUnix)
​
echo "SMBLastSet: " $smb_last_set_epoch
echo "ADPassmon: " $adpassmon_last_set```
``````

**Comment by macmule** [comment]
Also, out of curiosity.. can you try the below on wifi & on ethernet?

`````` #!/usr/bin/python

# OD API calls, thanks @tburgin

import sys
import subprocess
import time
from datetime import datetime, timedelta
from OpenDirectory import ODSession, \
                          ODNode, \
                          ODQuery, \
                          kODRecordTypeUsers, \
                          kODAttributeTypeRecordName, \
                          kODMatchEqualTo
from SystemConfiguration import SCDynamicStoreCreate, \
                                SCDynamicStoreCopyValue, \
                                SCDynamicStoreCopyConsoleUser

# Create net_config
net_config = SCDynamicStoreCreate(None, "net", None, None)

# Get AD info
ad_info = dict(SCDynamicStoreCopyValue(net_config, 'com.apple.opendirectoryd.ActiveDirectory'))

# Get node_name from above
node_name = ad_info['NodeName']

# Get domain DNS name from above
domain_dns = ad_info['DomainNameDns']

# Combine for node_name
ad_node = node_name + '/' + domain_dns

# Get user_name
user_name = SCDynamicStoreCopyConsoleUser(None, None, None)[0]

# Local node
local_node, _ = ODNode.nodeWithSession_name_error_(ODSession.defaultSession(), "/Local/Default", None)

# Local user account
local_user_record, _ = local_node.recordWithRecordType_name_attributes_error_(kODRecordTypeUsers, user_name, None, None)

# Get the values of from the user record
local_values, _ = local_user_record.recordDetailsForAttributes_error_(None, None)

# Get the accounts AD Node
#ad_node = local_values['dsAttrTypeStandard:Originalnode_name'][0]

# Set the OD Node
node, _ = ODNode.nodeWithSession_name_error_(ODSession.defaultSession(), ad_node, None)

# Get the users record
userRecord, _ = node.recordWithRecordType_name_attributes_error_(kODRecordTypeUsers, user_name, None, None)

# Get the values of from the user record
values, _ = userRecord.recordDetailsForAttributes_error_(None, None)

member_of = values['dsAttrTypeNative:memberOf']

user_groups = []
for groups in member_of:
    user_groups.append(groups.split(',')[0].strip('CN='))

# Get the realName
realName = values['dsAttrTypeStandard:RealName'][0]

# Get the user status
uAC = values['dsAttrTypeNative:userAccountControl'][0]

# Check the userAccountControl code,
# https://social.technet.microsoft.com/Forums/en-US/69211f96-b17e-43aa-9a6a-4f8e99ae2b3a/useraccountcontrol-and-employeestatus?forum=ilm2
disabledCodes = ["514", "546", "66050", "66082", "262658", "262690", "328194", "328226",]

# If enabled & pass expires
if uAC == "512":
    accountStatus = "Password Expires"
# If enabled & pass does not expire
elif uAC == "66048":
    accountStatus = "Password Does Not Expire"
# If disabled
elif any(s in uAC for s in disabledCodes):
    accountStatus = "Account Disabled"

# Default session
session = ODSession.defaultSession()

# Node to search
node, error = ODNode.nodeWithSession_name_error_(session, '/Search', None)

# Query OD
query, error = ODQuery.queryWithNode_forRecordTypes_attribute_matchType_queryValues_returnAttributes_maximumResults_error_(node, kODRecordTypeUsers, kODAttributeTypeRecordName, kODMatchEqualTo, user_name, ['msDS-UserPasswordExpiryTimeComputed'], 0, None)

# Return result
result, error = query.resultsAllowingPartial_error_(False, None)

# Return only AD
ad_records = [x for x in result if x.valueForKey_('dsAttrTypeStandard:AppleMetaNodeLocation')[0].lower().startswith('/active directory')]

# Get the attribute msDS-UserPasswordExpiryTimeComputed
userPwdExpiry = ad_records[0].valueForKey_('msDS-UserPasswordExpiryTimeComputed')[0]

# Get Password last set
pwdSetDateRaw = int(values['dsAttrTypeStandard:SMBPasswordLastSet'][0])

# Convert to a UNIX epoch time stamp
pwdSetDateUnix = pwdSetDateRaw / 10000000 - 11644473600

# Convert to readable
readableDate = time.strftime('%A, %d %B %Y %H:%M:%S', time.localtime(pwdSetDateUnix))

# Time now in Epoch Time
timeNow = int(time.time())

# Days since password was set
daysSinceSet = (timeNow - pwdSetDateUnix) / 86400

# Local var
ldapServersList = []
# Try & get LDAP servers
try:
    # Lookup for LDAP servers
    domainCheck = subprocess.check_output(['dig', '-t', 'srv', '_ldap._tcp.' + domain_dns, '+noall', '+answer']).splitlines()
    # Iterate over the above
    for index, item in enumerate(domainCheck):
        # If the above is an ldap server
        if item.startswith('_ldap._tcp.'):
            # Add to list
            ldapServersList.append(item.split()[7].rstrip('.'))
except:
    # Print error
    print 'ERROR: No LDAP servers can be found'
    # Exit
    sys.exit(1)

ldap_attempts = 1
# If fails move to next LDAP
for ldapServer in ldapServersList:
    try:
        # Get search base.. TO ADD increment if fails with next entry in ldapServer
        searchBase = subprocess.check_output(['ldapsearch', '-LLL', '-Q', '-s', 'base', '-H', 'ldap://' + ldapServer, 'defaultNamingContext']).splitlines()
        break
    except:
        ldap_attempts = ldap_attempts + 1
        continue

# Get search base.. ewww
for index, item in enumerate(searchBase):
    if item.startswith('defaultNamingContext:'):
        mySearchBase = item.split(':')[1].strip()

# If fails move to next LDAP
for ldapServer in ldapServersList:
    try:
        # LDAP lookup for maxPwdAge attribute, output split line by line
        passwordAgeDays = subprocess.check_output(['ldapsearch', '-LLL', '-Q', '-s', 'base', '-H', 'ldap://' + ldapServer, '-b', mySearchBase, 'maxPwdAge']).splitlines()
        break
    except:
        ldap_attempts = ldap_attempts + 1
        continue

if ldap_attempts == len(ldapServersList):
    print 'LDAP Max Password failed'
else:
    # Iterate over returned data
    for maxAge in passwordAgeDays:
        # If the line starts maxPwdAge
        if maxAge.startswith('maxPwdAge:'):
            # Split, return the number & convert
            passwordExpiry = int(maxAge.split(':')[1]) / 10000000 / 86400 / -1

if not userPwdExpiry:
    # Get time pass expires
    pwdExpires = (datetime.fromtimestamp(pwdSetDateUnix) + timedelta(passwordExpiry)).strftime('%A, %d %B %Y %H:%M:%S')
    pwcCalc = "LDAP"
else:
    pwdExpires = (datetime.fromtimestamp(int(userPwdExpiry) / 10000000 - 11644473600)).strftime('%A, %d %B %Y %H:%M:%S')
    pwdCalc = "ms-DS"

print
# Summary
print '------ SUMMARY ------'
print 'LDAP servers found: %s' % len(ldapServersList)
print 'LDAP server queried: %s' % ldapServer
print 'LDAP lookup attempts: %s' % ldap_attempts
print 'Search base: %s' % mySearchBase
print 'AD Node: %s' % ad_node
print 'user_name: %s ' % user_name
print 'uAC: %s' % uAC
print 'Password Status: %s' % accountStatus
print 'pwdSetDateRaw: %s' % pwdSetDateRaw
print 'Epoch Set Date: % s' % pwdSetDateUnix
print 'Set Date: %s' % readableDate
print 'Epoch Now: %s' % timeNow
print 'Password Age: %s' % passwordExpiry
print 'Days since set: %s' % daysSinceSet
print 'Password Expires in: %s ' % (passwordExpiry - daysSinceSet)
print 'Password Expires: %s' % pwdExpires
print 'Expiration Calc : %s' % pwdCalc
#print 'User Groups: %s' % len(user_groups)
#print 'Group Memberships: %s' % user_groups```
``````

**Comment by MacDogbert** [comment]
Thanks Ben.

On WiFi (after running "Re-check Expiration" from menubar icon):
(I tweaked this a bit to get it to run:)

```
smb_last_set=$(/usr/bin/dscl localhost read "/Search/Users/userid" SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}' | tail -n 1)
smb_last_set_epoch=$(echo $(expr $smb_last_set / 10000000 - 11644473600))

adpassmon_last_set=$(/usr/bin/defaults read org.pmbuko.ADPassMon expireDateUnix)

echo "SMBLastSet:  $smb_last_set_epoch"
echo "ADPassmon: $adpassmon_last_set"

SMBLastSet:  1462468519 #(Thu May  5 12:15:19 CDT 2016) *correct
ADPassmon: 1462468607 #(Thu May  5 12:16:47 CDT 2016) *nope, should be 1467652519 (Mon Jul  4 12:15:19 CDT 2016)
```

python script:
On LAN:

```
LDAP servers found: 8
LDAP server queried: server.yup.thatsright.com
LDAP lookup attempts: 1
Search base: DC=yup,DC=thatsright,DC=com
AD Node: /Active Directory/OUNAME/yup.thatsright.com
user_name: userid 
uAC: 512
Password Status: Password Expires
pwdSetDateRaw: 131069421197596111
Epoch Set Date: 1462468519
Set Date: Thursday, 05 May 2016 12:15:19
Epoch Now: 1462996088
Password Age: 60
Days since set: 6
Password Expires in: 54 
Password Expires: Monday, 04 July 2016 12:15:19
Expiration Calc : ms-DS
```

On WiFi:

I ran into errors on WiFi...not sure if there is something I can tweak to get this to work or if the script needs to contact a DC:

```
python ./adpasspython.py
Traceback (most recent call last):
File "./adpasspython.py", line 51, in <module>
userRecord, _ = node.recordWithRecordType_name_attributes_error_(kODRecordTypeUsers, user_name, None, None)
AttributeError: 'NoneType' object has no attribute 'recordWithRecordType_name_attributes_error_'
```

**Comment by macmule** [comment]
Ok.. this is great.

What does this bring back on Wifi & on LAN?

`/usr/bin/dscl localhost read /Search/Users/"$USER" SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}'`

**Comment by macmule** [comment]
[ADPassMon.zip](https://github.com/macmule/ADPassMon/files/260207/ADPassMon.zip)

Can you try ^^?

**Comment by MacDogbert** [comment]
On LAN:

```
/usr/bin/dscl localhost read /Search/Users/userid SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}'
131069421197596111
131069421197596111
```

On WiFi:

```
/usr/bin/dscl localhost read /Search/Users/userid SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}'
131069421197596111 #only one value
```

New version (2.20.20) -- This **new version has resolved this issue**, the expiration is remaining correct regardless of connectivity. Thank you Ben, let me know if you need any more data.

Logs and plist values from new version below. 

LAN:

```
5/12/16 7:16:03.973 AM ADPassMon[1136]: Domain reachable.
5/12/16 7:16:03.973 AM ADPassMon[1136]: Starting auto process…
5/12/16 7:16:03.974 AM ADPassMon[1136]:   Found expireDateUnix in plist: 1.467652519E+9
5/12/16 7:16:04.330 AM ADPassMon[1136]:   Got expireDateUnix: 1467652519
5/12/16 7:16:04.330 AM ADPassMon[1136]:   Using msDS method
5/12/16 7:16:04.340 AM ADPassMon[1136]:     daysUntilExp: 53.2078125
5/12/16 7:16:04.343 AM ADPassMon[1136]: ADPassMon password method selected
5/12/16 7:16:04.343 AM ADPassMon[1136]: Testing Keychain Lock state...
5/12/16 7:16:04.375 AM ADPassMon[1136]:   Keychain unlocked...

defaults read org.pmbuko.adpassmon
{
    accTest = 0;
    enableKeychainLockCheck = 1;
    expireDateUnix = 1467652519;
    "first_run" = 0;
    isBehaviour2Enabled = 1;
    "menu_title" = 53d;
    pwdSetDate = "16926.72";
    selectedBehaviour = 2;
    tooltip = "Your password expires\\nMon Jul  4 12:15:19 CDT 2016";
}

```

WiFi:

```
5/12/16 7:16:28.820 AM ADPassMon[1136]: Domain reachable.
5/12/16 7:16:28.821 AM ADPassMon[1136]: Starting auto process…
5/12/16 7:16:28.821 AM ADPassMon[1136]:   Found expireDateUnix in plist: 1467652519
5/12/16 7:16:28.858 AM ADPassMon[1136]:   Using alt method
5/12/16 7:16:28.890 AM ADPassMon[1136]:   New pwdSetDate (16926.72)
5/12/16 7:16:28.890 AM ADPassMon[1136]:   ≥ plist value (1.692672E+4) so we use it
5/12/16 7:16:28.900 AM ADPassMon[1136]: ADPassMon password method selected
5/12/16 7:16:28.900 AM ADPassMon[1136]: Testing Keychain Lock state...
5/12/16 7:16:28.936 AM ADPassMon[1136]:   Keychain unlocked...

{
    accTest = 0;
    enableKeychainLockCheck = 1;
    expireDateUnix = 1467652519;
    "first_run" = 0;
    isBehaviour2Enabled = 1;
    "menu_title" = 53d;
    pwdSetDate = "16926.72";
    selectedBehaviour = 2;
    tooltip = "Your password expires\\nMon Jul  4 12:15:19 CDT 2016";
}

```

(I don't know my GitHub etiquette so I'm just going to click "Comment" instead of "Close and comment") :)

**Comment by macmule** [comment]
Great.

This was a hack around the issue to help isolate the cause.

I commented out two functions & used the "offlineUpdate" instead:

```
                else
                    log "  Using alt method"
                    getPwdSetDate_(me)
                    --compareDates_(me)
                    --getExpirationDate_(daysUntilExp)
                    offlineUpdate_(me)
                end if
```

I'll need to review to see if this is ideal going forward.

**Comment by kgthenerd** [comment]
<img width="374" alt="screen shot 2016-05-19 at 6 13 06 pm" src="https://cloud.githubusercontent.com/assets/195539/15393946/9251eb92-1ded-11e6-818e-ab7fb869a85d.png">
The password is updated on AD, yet it shows -1d left

**Comment by MacDogbert** [comment]
@kgthenerd If you are seeing the `-1d` under similar circumstances as described in this issue then I recommend testing the Pre-Release version (2.20.20), it resolves this issue for me.
https://github.com/macmule/ADPassMon/releases

**Comment by kgthenerd** [comment]
I'm running 2.20.20 (145) atm

**Comment by macmule** [comment]
@kgthenerd Can you run recheck the expiration then post the log?

**Comment by kgthenerd** [comment]
19/05/16 10:34:41.142 PM ADPassMon[694]: Domain reachable.
19/05/16 10:34:41.143 PM ADPassMon[694]: Starting auto process…
19/05/16 10:34:41.144 PM ADPassMon[694]:   Found expireDateUnix in plist: 1.463554656E+9
19/05/16 10:34:41.505 PM ADPassMon[694]:   Using alt method
19/05/16 10:34:41.533 PM ADPassMon[694]:   New pwdSetDate (16849.29)
19/05/16 10:34:41.533 PM ADPassMon[694]:   ≥ plist value (1.684929E+4) so we use it
19/05/16 10:34:41.542 PM ADPassMon[694]: Triggering notification…
19/05/16 10:34:41.543 PM ADPassMon[694]: Native password method selected
19/05/16 10:34:41.543 PM ADPassMon[694]: Testing Universal Access settings…
19/05/16 10:34:41.543 PM ADPassMon[694]:   Enabled
19/05/16 10:34:41.544 PM ADPassMon[694]: Skipping Keychain Lock state check...

**Comment by karlmikaelskar** [comment]
I still have this issue with version 2.20.20

/usr/bin/dscl localhost read /Search/Users/$USERNAME SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}' 

> 131080414033089474

defaults read org.pmbuko.adpassmon

> {
>     accTest = 0;
>     enableKeychainLockCheck = 1;
>     expireAge = "";
>     expireDateUnix = 1479119803;
>     "first_run" = 0;
>     isBehaviour2Enabled = 1;
>     "menu_title" = "-41798d";
>     passExpires = 0;
>     passwordCheckInterval = 4;
>     pwdSetDate = "16126.55";
>     selectedBehaviour = 2;
>     selectedMethod = 0;
>     tooltip = "Your password expires\nMon Nov 14 11:36:43 CET 2016";
> }

System.log (On wifi, from home, no VPN.)

> May 22 16:54:15 CI0010848 ADPassMon[16295]: Domain test timed out.

**Yesterday** this was my state in the plist and menu bar showed the correct date:
defaults read org.pmbuko.adpassmon

> {
>     accTest = 0;
>     enableKeychainLockCheck = 1;
>     expireAge = "";
>     expireDateUnix = 1479119803;
>     "first_run" = 0;
>     isBehaviour2Enabled = 1;
>     "menu_title" = 177d;
>     passExpires = 0;
>     passwordCheckInterval = 4;
>     pwdSetDate = "16126.55";
>     selectedBehaviour = 2;
>     selectedMethod = 0;
>     tooltip = "Your password expires\nMon Nov 14 11:36:43 CET 2016";
> }

**Comment by karlmikaelskar** [comment]
Correction: Negative expiration days are fixed. Negative faulty value is in another issue.

**Comment by kdbo** [comment]
I  still have the same issue with the latest version and with AD reachable.
WIFI -> IPSec VPN
Haven't tried LAN yet.

![screen shot 2016-07-02 at 15](https://cloud.githubusercontent.com/assets/5040711/16540695/9e22b0ee-406d-11e6-9aa1-484d6323a05c.png)

> Jul  2 15:45:26 koenmbp ADPassMon[4784]: Performance: Please update this scripting addition to supply a value for ThreadSafe for each event handler: "/Library/ScriptingAdditions/SIMBL.osax"
> Jul  2 15:45:26 koenmbp ADPassMon[4784]: Running on OS 10.10.x
> Jul  2 15:45:26 koenmbp ADPassMon[4784]: Running under a locally cached network account.
> Jul  2 15:45:27 koenmbp ADPassMon[4784]: Native password method selected
> Jul  2 15:45:27 koenmbp ADPassMon[4784]: Testing Universal Access settings…
> Jul  2 15:45:27 koenmbp ADPassMon[4784]:   Enabled
> Jul  2 15:45:27 koenmbp ADPassMon[4784]: Domain reachable.
> Jul  2 15:45:27 koenmbp ADPassMon[4784]: Testing if password can expire…
> Jul  2 15:45:27 koenmbp ADPassMon[4784]:   Password does expire.
> Jul  2 15:45:27 koenmbp ADPassMon[4784]: Domain reachable.
> Jul  2 15:45:27 koenmbp ADPassMon[4784]: Starting auto process…
> Jul  2 15:45:27 koenmbp ADPassMon[4784]:   Found expireDateUnix in plist: 14743667
> Jul  2 15:45:27 koenmbp ADPassMon[4784]:   Using alt method
> Jul  2 15:45:28 koenmbp ADPassMon[4784]:   New pwdSetDate (16881.43)
> Jul  2 15:45:28 koenmbp ADPassMon[4784]:   ≥ plist value (1,688143E+4) so we use it
> Jul  2 15:45:28 koenmbp ADPassMon[4784]: Triggering notification…
> Jul  2 15:45:28 koenmbp ADPassMon[4784]: Native password method selected
> Jul  2 15:45:28 koenmbp ADPassMon[4784]: Testing Universal Access settings…
> Jul  2 15:45:28 koenmbp ADPassMon[4784]:   Enabled
> Jul  2 15:45:28 koenmbp ADPassMon[4784]: Testing Keychain Lock state...
> Jul  2 15:45:28 koenmbp ADPassMon[4784]:   Keychain unlocked...
> 
> defaults read org.pmbuko.ADPassMon
> {
>     accTest = 0;
>     enableKeychainLockCheck = 1;
>     expireAge = 183;
>     expireDateUnix = 14743667;
>     "first_run" = 0;
>     isBehaviour2Enabled = 0;
>     "menu_title" = "-16813d";
>     pwdSetDate = "16881.43";
>     runIfLocal = 0;
>     selectedBehaviour = 1;
>     tooltip = "Your password expires\n";
> }

**Comment by macmule** [comment]
Please test: https://github.com/macmule/ADPassMon/releases/tag/154

**Comment by kgthenerd** [comment]
Still there 
<img width="61" alt="screen shot 2016-11-08 at 7 27 34 am" src="https://cloud.githubusercontent.com/assets/195539/20083874/ee128bca-a584-11e6-8c61-a8d1e542f481.png">
<img width="280" alt="screen shot 2016-11-08 at 7 27 45 am" src="https://cloud.githubusercontent.com/assets/195539/20083877/f1422b66-a584-11e6-9e19-521b5083b3ca.png">

**Comment by macmule** [comment]
@kgthenerd & what's in the logs?

**Comment by kgthenerd** [comment]
> Tue Nov 8 13:04:44 IST 2016 Domain test succeeded.
> Tue Nov 8 13:04:44 IST 2016 Domain test succeeded.
> Tue Nov 8 13:04:45 IST 2016 myDomain: domain.com
> Tue Nov 8 13:04:45 IST 2016 myLDAP: ads.domain.com.
> Tue Nov 8 13:04:45 IST 2016 Using alt method
> Tue Nov 8 13:04:45 IST 2016 mySearchBase: 
> Tue Nov 8 13:04:46 IST 2016 Couldn't get expireAge. Trying using Manual method.
> Tue Nov 8 13:04:46 IST 2016 pwdSetDateUnix via DSCL: 131002526829933846
> Tue Nov 8 13:04:46 IST 2016 pwdSetDate epoch: 1455779000
> Tue Nov 8 13:04:46 IST 2016 Today epoch: 1478590486
> Tue Nov 8 13:04:46 IST 2016 Days Since Set: 264.021828703704
> Tue Nov 8 13:04:46 IST 2016 alt daysUntilExp: -174.021828703704
> Tue Nov 8 13:04:46 IST 2016 alt daysUntilExpNice: -175
> Tue Nov 8 13:04:46 IST 2016 alt secondsTilExpiry: -15035490
> Tue Nov 8 13:04:46 IST 2016 Got expireDateUnix from alt: 1463555000
> Tue Nov 8 13:04:46 IST 2016 expirationDate: Wed May 18 12:33:20 IST 2016
> Tue Nov 8 13:04:46 IST 2016 Triggering notification…
> Tue Nov 8 13:04:46 IST 2016 Native password method selected
> Tue Nov 8 13:04:46 IST 2016 Testing Universal Access settings…
> Tue Nov 8 13:04:47 IST 2016 Skipping Accessibility check...
> Tue Nov 8 13:04:47 IST 2016 Skipping Keychain Lock state check...
> Tue Nov 8 13:05:02 IST 2016 Testing for Kerberos ticket…
> Tue Nov 8 13:05:03 IST 2016 Kerberos ticket expired or not found
> Tue Nov 8 13:05:04 IST 2016 User chose not to acquire
> Tue Nov 8 13:05:04 IST 2016 Script Error: The command exited with a non-zero status.
> Tue Nov 8 13:05:07 IST 2016 Starting auto process…
> Tue Nov 8 13:05:07 IST 2016 Domain test succeeded.
> Tue Nov 8 13:05:07 IST 2016 Domain test succeeded.
> Tue Nov 8 13:05:08 IST 2016 myDomain: domain.com
> Tue Nov 8 13:05:08 IST 2016 myLDAP: ads.domain.com.
> Tue Nov 8 13:05:08 IST 2016 Using alt method
> Tue Nov 8 13:05:09 IST 2016 mySearchBase: 
> Tue Nov 8 13:05:09 IST 2016 Couldn't get expireAge. Trying using Manual method.
> Tue Nov 8 13:05:09 IST 2016 pwdSetDateUnix via DSCL: 131002526829933846
> Tue Nov 8 13:05:10 IST 2016 pwdSetDate epoch: 1455779000
> Tue Nov 8 13:05:10 IST 2016 Today epoch: 1478590510
> Tue Nov 8 13:05:10 IST 2016 Days Since Set: 264.022106481482
> Tue Nov 8 13:05:10 IST 2016 alt daysUntilExp: -174.022106481482
> Tue Nov 8 13:05:10 IST 2016 alt daysUntilExpNice: -175
> Tue Nov 8 13:05:10 IST 2016 alt secondsTilExpiry: -15035510
> Tue Nov 8 13:05:10 IST 2016 Got expireDateUnix from alt: 1463555000
> Tue Nov 8 13:05:10 IST 2016 expirationDate: Wed May 18 12:33:20 IST 2016
> Tue Nov 8 13:05:10 IST 2016 Triggering notification…
> Tue Nov 8 13:05:10 IST 2016 Native password method selected
> Tue Nov 8 13:05:10 IST 2016 Testing Universal Access settings…
> Tue Nov 8 13:05:10 IST 2016 Skipping Accessibility check...
> Tue Nov 8 13:05:10 IST 2016 Skipping Keychain Lock state check...
> Tue Nov 8 13:06:11 IST 2016 Starting auto process…
> Tue Nov 8 13:06:11 IST 2016 Domain test succeeded.
> Tue Nov 8 13:06:12 IST 2016 Domain test succeeded.
> Tue Nov 8 13:06:12 IST 2016 myDomain: domain.com
> Tue Nov 8 13:06:12 IST 2016 myLDAP: ads.domain.com.
> Tue Nov 8 13:06:12 IST 2016 Using alt method
> Tue Nov 8 13:06:13 IST 2016 mySearchBase: 
> Tue Nov 8 13:06:14 IST 2016 Couldn't get expireAge. Trying using Manual method.
> Tue Nov 8 13:06:14 IST 2016 pwdSetDateUnix via DSCL: 131002526829933846
> Tue Nov 8 13:06:14 IST 2016 pwdSetDate epoch: 1455779000
> Tue Nov 8 13:06:14 IST 2016 Today epoch: 1478590574
> Tue Nov 8 13:06:14 IST 2016 Days Since Set: 264.022847222222
> Tue Nov 8 13:06:14 IST 2016 alt daysUntilExp: -174.022847222222
> Tue Nov 8 13:06:14 IST 2016 alt daysUntilExpNice: -175
> Tue Nov 8 13:06:14 IST 2016 alt secondsTilExpiry: -15035570
> Tue Nov 8 13:06:14 IST 2016 Got expireDateUnix from alt: 1463555000
> Tue Nov 8 13:06:14 IST 2016 expirationDate: Wed May 18 12:33:20 IST 2016
> Tue Nov 8 13:06:14 IST 2016 Triggering notification…
> Tue Nov 8 13:06:14 IST 2016 Native password method selected
> Tue Nov 8 13:06:14 IST 2016 Testing Universal Access settings…
> Tue Nov 8 13:06:14 IST 2016 Skipping Accessibility check...
> Tue Nov 8 13:06:14 IST 2016 Skipping Keychain Lock state check...
> Tue Nov 8 13:09:16 IST 2016 Starting auto process…
> Tue Nov 8 13:09:16 IST 2016 Domain test succeeded.
> Tue Nov 8 13:09:16 IST 2016 Domain test succeeded.
> Tue Nov 8 13:09:17 IST 2016 myDomain: domain.com
> Tue Nov 8 13:09:17 IST 2016 myLDAP: qtadvic01.domain.com.
> Tue Nov 8 13:09:17 IST 2016 Using alt method
> Tue Nov 8 13:09:18 IST 2016 mySearchBase: 
> Tue Nov 8 13:09:18 IST 2016 Couldn't get expireAge. Trying using Manual method.
> Tue Nov 8 13:09:18 IST 2016 pwdSetDateUnix via DSCL: 131002526829933846
> Tue Nov 8 13:09:18 IST 2016 pwdSetDate epoch: 1455779000
> Tue Nov 8 13:09:18 IST 2016 Today epoch: 1478590758
> Tue Nov 8 13:09:18 IST 2016 Days Since Set: 264.024976851852
> Tue Nov 8 13:09:18 IST 2016 alt daysUntilExp: -174.024976851852
> Tue Nov 8 13:09:18 IST 2016 alt daysUntilExpNice: -175
> Tue Nov 8 13:09:18 IST 2016 alt secondsTilExpiry: -15035760
> Tue Nov 8 13:09:18 IST 2016 Got expireDateUnix from alt: 1463555000
> Tue Nov 8 13:09:18 IST 2016 expirationDate: Wed May 18 12:33:20 IST 2016
> Tue Nov 8 13:09:19 IST 2016 Triggering notification…
> Tue Nov 8 13:09:19 IST 2016 Native password method selected
> Tue Nov 8 13:09:19 IST 2016 Testing Universal Access settings…
> Tue Nov 8 13:09:19 IST 2016 Skipping Accessibility check...
> Tue Nov 8 13:09:19 IST 2016 Skipping Keychain Lock state check...
> Tue Nov 8 13:11:04 IST 2016 Testing for Kerberos ticket…
> Tue Nov 8 13:11:04 IST 2016 Kerberos ticket expired or not found
> Tue Nov 8 13:11:11 IST 2016 Ticket acquired
> Tue Nov 8 13:11:12 IST 2016 Testing for Kerberos ticket…
> Tue Nov 8 13:11:13 IST 2016 Ticket found and renewed
> Tue Nov 8 13:11:13 IST 2016 Retrieving defaults..
> Tue Nov 8 13:11:13 IST 2016 Starting auto process…
> Tue Nov 8 13:11:13 IST 2016 Domain test succeeded.
> Tue Nov 8 13:11:13 IST 2016 Domain test succeeded.
> Tue Nov 8 13:11:13 IST 2016 myDomain: domain.com
> Tue Nov 8 13:11:13 IST 2016 myLDAP: ads.domain.com.
> Tue Nov 8 13:11:14 IST 2016 Using alt method
> Tue Nov 8 13:11:16 IST 2016 mySearchBase: DC=domain,DC=com
> Tue Nov 8 13:11:17 IST 2016 Got expireAge: 90
> Tue Nov 8 13:11:17 IST 2016 pwdSetDateUnix via DSCL: 131002526829933846
> Tue Nov 8 13:11:17 IST 2016 pwdSetDate epoch: 1455779000
> Tue Nov 8 13:11:17 IST 2016 Today epoch: 1478590877
> Tue Nov 8 13:11:17 IST 2016 Days Since Set: 264.026354166667
> Tue Nov 8 13:11:17 IST 2016 alt daysUntilExp: -174.026354166667
> Tue Nov 8 13:11:17 IST 2016 alt daysUntilExpNice: -175
> Tue Nov 8 13:11:17 IST 2016 alt secondsTilExpiry: -15035880
> Tue Nov 8 13:11:17 IST 2016 Got expireDateUnix from alt: 1463555000
> Tue Nov 8 13:11:17 IST 2016 expirationDate: Wed May 18 12:33:20 IST 2016
> Tue Nov 8 13:11:17 IST 2016 Triggering notification…
> Tue Nov 8 13:11:17 IST 2016 Native password method selected
> Tue Nov 8 13:11:17 IST 2016 Testing Universal Access settings…
> Tue Nov 8 13:11:17 IST 2016 Skipping Accessibility check...
> Tue Nov 8 13:11:17 IST 2016 Skipping Keychain Lock state check...
> Tue Nov 8 13:11:22 IST 2016 Starting auto process…
> Tue Nov 8 13:11:22 IST 2016 Domain test succeeded.
> Tue Nov 8 13:11:22 IST 2016 Domain test succeeded.
> Tue Nov 8 13:11:23 IST 2016 myDomain: domain.com
> Tue Nov 8 13:11:23 IST 2016 myLDAP: ads.domain.com.
> Tue Nov 8 13:11:23 IST 2016 Using alt method
> Tue Nov 8 13:11:25 IST 2016 mySearchBase: DC=domain,DC=com
> Tue Nov 8 13:11:26 IST 2016 Got expireAge: 90
> Tue Nov 8 13:11:26 IST 2016 pwdSetDateUnix via DSCL: 131002526829933846
> Tue Nov 8 13:11:26 IST 2016 pwdSetDate epoch: 1455779000
> Tue Nov 8 13:11:26 IST 2016 Today epoch: 1478590886
> Tue Nov 8 13:11:26 IST 2016 Days Since Set: 264.026458333333
> Tue Nov 8 13:11:26 IST 2016 alt daysUntilExp: -174.026458333333
> Tue Nov 8 13:11:27 IST 2016 alt daysUntilExpNice: -175
> Tue Nov 8 13:11:27 IST 2016 alt secondsTilExpiry: -15035890
> Tue Nov 8 13:11:27 IST 2016 Got expireDateUnix from alt: 1463555000
> Tue Nov 8 13:11:27 IST 2016 expirationDate: Wed May 18 12:33:20 IST 2016
> Tue Nov 8 13:11:27 IST 2016 Triggering notification…
> Tue Nov 8 13:11:27 IST 2016 Native password method selected
> Tue Nov 8 13:11:27 IST 2016 Testing Universal Access settings…
> Tue Nov 8 13:11:27 IST 2016 Skipping Accessibility check...
> Tue Nov 8 13:11:27 IST 2016 Skipping Keychain Lock state check...

**Comment by macmule** [comment]
So, we're not able to get the expiry age from LDAP.. or msDS.. so you've set it manually to 90 days.

dscl is able to grab the `SMBPasswordLastSet` value which is: 131002526829933846, once converted to time since epoch in seconds (via 131002526829933846 /  10000000 - 11644473600).. that gives: 1455779082.

Which is a date of: GMT: Thu, 18 Feb 2016 07:04:42 GMT.

90 Days from that is: GMT: Wed, 18 May 2016 07:03:20 GMT, which is -175 days ago.

So, ADPassMon is correct in what it's displaying with the information it can get.

What does `/usr/bin/dscl localhost read /Search/Users/$USER  SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}'` output?

**Comment by kgthenerd** [comment]
> /usr/bin/dscl localhost read /Search/Users/$USER SMBPasswordLastSet | /usr/bin/awk '/LastSet:/{print $2}'
> 131002526829933846

**Comment by macmule** [comment]
@kgthenerd Right, so as said dscl is showing that the password as set on 131002526829933846 which is 1455779082 in epoch & then gives a date of GMT: Thu, 18 Feb 2016 07:04:42 GMT.

Which is about 264/5 days ago, & if you then take of the 90 day expiry you'll see: -175days.

The issue posted by @MacDogbert is more to do with it being right once, then going to minus days depending on connectivity.

@kgthenerd If that accounts password is changed today, do things correct? If ADPassMon cannot pull in the right information, there's not much I can suggest.

**Comment by kgthenerd** [comment]
Let me try rejoining the AD on this mac, maybe that would resolve this issue.

**Comment by macmule** [comment]
@kgthenerd Is this a mobile account or a network account?

**Comment by kgthenerd** [comment]
~~network account i believe~~
It's a mobile account

**Comment by macmule** [comment]
That's odd, as a network account should not be able to login is bad AD bind.

But, please report back what you see.

**Comment by macmule** [comment]
@kgthenerd ahh.. didn't see the update.. did rebinding work?

**Comment by macmule** [comment]
Please test: https://github.com/macmule/ADPassMon/releases/tag/163

@MacDogbert, @kgthenerd, @karlmikaelskar, @kdbo

**Comment by macmule** [comment]
Hi folks,

ADPassmon is no longer maintained, please use [NoMAD](https://www.nomad.menu).

As such, i'm closing this off.
